# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

oaggregate <- function(micro, th) {
    .Call(`_lpaggregr_oaggregate`, micro, th)
}

haggregate <- function(micro, h, th) {
    .Call(`_lpaggregr_haggregate`, micro, h, th)
}

daggregate <- function(micro, h, th) {
    .Call(`_lpaggregr_daggregate`, micro, h, th)
}

